### PR TITLE
Fix db type error, when hostgroup is accidentially interpreted as integer

### LINKED ISSUE #2821: icinga hostgroup object_name interpretet as integer causes postgres error
## Expected Behavior
Hostgroups can have simple numbers as object_name and matching can also done with integers.

## Current Behavior
Activitylog detail tab and some other pages are not displayed. Instead a stacktrace is shown.

## Possible Solution
My temporary solution is to check for integer value and convert it to string -> this is a bit ugly but does the job.

director/library/Director/Objects/IcingaObjectGroups.php:186
```php
         if (is_int($group)) {
             $group = "$group";
         }
```

## Steps to Reproduce (for bugs)
icingacli director hostgroup create "5" --json "{\"display_name\":\"Test\"}"
pull an element in via director import run (in my case via sql query)
This element in my case has a type 5 which will be matched to the hostgroup
when trying to sync/roll out the following stacktrace is shown:
grafik

```
SQLSTATE[42883]: Undefined function: 7 ERROR: operator does not exist: character varying = integer
ZEILE 1: ...ga_hostgroup.* FROM icinga_hostgroup WHERE (object_name = 5)
^
TIP: No operator matches the given name and argument types. You might need to add explicit type casts., query was: SELECT icinga_hostgroup.* FROM icinga_hostgroup WHERE (object_name = 5)

#0 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute()
#1 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute()
#2 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Db/Adapter/Pdo/Abstract.php(265): Zend_Db_Adapter_Abstract->query()
#3 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Db/Adapter/Abstract.php(759): Zend_Db_Adapter_Pdo_Abstract->query()
#4 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(725): Zend_Db_Adapter_Abstract->fetchRow()
#5 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(1324): Icinga\Module\Director\Data\Db\DbObject->loadFromDb()
#6 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObjectGroups.php(203): Icinga\Module\Director\Data\Db\DbObject::load()
#7 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObjectGroups.php(181): Icinga\Module\Director\Objects\IcingaObjectGroups->add()
#8 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObjectGroups.php(140): Icinga\Module\Director\Objects\IcingaObjectGroups->add()
#9 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(1163): Icinga\Module\Director\Objects\IcingaObjectGroups->set()
#10 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(349): Icinga\Module\Director\Objects\IcingaObject->setGroups()
#11 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(791): Icinga\Module\Director\Data\Db\DbObject->set()
#12 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(480): Icinga\Module\Director\Objects\IcingaObject->set()
#13 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(733): Icinga\Module\Director\Data\Db\DbObject->setProperties()
#14 /usr/share/icingaweb2/modules/director/library/Director/Web/Widget/ActivityLogInfo.php(632): Icinga\Module\Director\Objects\IcingaObject->setProperties()
#15 /usr/share/icingaweb2/modules/director/library/Director/Web/Widget/ActivityLogInfo.php(429): Icinga\Module\Director\Web\Widget\ActivityLogInfo->createObject()
#16 /usr/share/icingaweb2/modules/director/library/Director/Web/Widget/ActivityLogInfo.php(464): Icinga\Module\Director\Web\Widget\ActivityLogInfo->newObject()
#17 /usr/share/icingaweb2/modules/director/library/Director/Web/Widget/ActivityLogInfo.php(132): Icinga\Module\Director\Web\Widget\ActivityLogInfo->newConfig()
#18 /usr/share/icingaweb2/modules/director/application/controllers/ConfigController.php(224): Icinga\Module\Director\Web\Widget\ActivityLogInfo->showTab()
#19 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Controller/Action.php(516): Icinga\Module\Director\Controllers\ConfigController->activityAction()
#20 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch()
#21 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Controller/Front.php(954): Icinga\Web\Controller\Dispatcher->dispatch()
#22 /usr/share/php/Icinga/Application/Web.php(294): Zend_Controller_Front->dispatch()
#23 /usr/share/php/Icinga/Application/webrouter.php(105): Icinga\Application\Web->dispatch()
#24 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#25 {main}
```

## Your Environment
* Director version (System - About): 1.11.0
* Icinga Web 2 version and modules (System - About): 2.12.0
* Icinga 2 version (`icinga2 --version`): r2.14.0-1
* Operating System and version: CentOS 7
* Webserver, PHP versions: php 8.0.30, Apache

maybe related to #2297

### PR DESCRIPTION
**Pull request by cschra**
fixes #2821

### CODE REVIEW

**Comment by bobapple** [comment]
The signed CLA is missing one or more GitHub usernames.

File: library/Director/Objects/IcingaObjectGroups.php [hunk 1]
```diff
@@ -183,6 +183,10 @@ public function add($group, $onError = 'fail')
             return $this;
         }
 
+         if (is_int($group)) {
+             $group = "$group";
```
Comment (Thomas-Gelf) [inline library/Director/Objects/IcingaObjectGroups.php:187]: Please use `$group = (int) $group;` instead of `"$group"`

**Review by Thomas-Gelf — CHANGES_REQUESTED** [review]

**Comment by cschra** [comment]
> The signed CLA is missing one or more GitHub usernames.

sorry for the inconvinience, I submitted a new one

File: library/Director/Objects/IcingaObjectGroups.php (hunk 1 above)
Comment (cschra) [reply library/Director/Objects/IcingaObjectGroups.php:187]: this is what I am trying to avoid - `$group` already is an integer at this point, hence i could cast it to string if you don't like the quotations....

Comment (Thomas-Gelf) [reply library/Director/Objects/IcingaObjectGroups.php:187]: My bad, this should of course have read "Please use `$group = (string) $group;`"

Comment (cschra) [reply library/Director/Objects/IcingaObjectGroups.php:187]: to keep the footprint small I amended the change to the existing commit (now [917d62a](https://github.com/Icinga/icingaweb2-module-director/pull/2822/commits/917d62ad5aab5b954132095cd5f3cd6affe26c5d))

**Comment by bobapple** [comment]
@cla-bot check

**Review by Thomas-Gelf — APPROVED** [review]

**Comment by Thomas-Gelf** [comment]
Please remove the superfluous indentation character on all three lines, to address Code Sniffer complaints. Then this is ready to be merged.

**Comment by cschra** [comment]
> Please remove the superfluous indentation character on all three lines, to address Code Sniffer complaints. Then this is ready to be merged.

done

**Comment by Thomas-Gelf** [comment]
Merged, thank you!
